producer:
  bootstrap: localhost:9092
  brokers: localhost:9092
  producttopic: request_log
  partitionCount: 1
  acks: all
  retries: 3
  minPoolSize: 80
  maxPoolSize: 120
  filePath: /Users/raghugupta/Documents/ApacheCassandra_CaseStudies/http-server.log.txt 